@extends('layouts.app')
@section('title','Vista general')
@section('content')
<div class="page-heading"><div><span class="eyebrow">TU NEGOCIO, DE UN VISTAZO</span><h1>Todo bajo control.</h1><p>Ventas, existencias y lo que necesita tu atención.</p></div><a class="btn" href="{{ route('sales') }}#nueva-venta">＋ Registrar venta</a></div>
<div class="stats">@foreach([['Ventas del mes',number_format($monthRevenue,2,',','.').' €','↗','Ingresos registrados'],['Productos activos',$productCount,'▦','Referencias en catálogo'],['Valor del inventario',number_format($stockValue,2,',','.').' €','▥','A precio de venta'],['Stock bajo',$lowStock->count(),'!','Productos por reponer']] as [$label,$value,$icon,$note])<div class="card stat"><div class="stat-top"><span>{{ $label }}</span><span class="stat-icon">{{ $icon }}</span></div><div class="stat-value">{{ $value }}</div><div class="stat-foot">{{ $note }}</div></div>@endforeach</div>
<div class="grid-two"><section class="card"><div class="card-header"><div><h2>Evolución de ventas</h2><p>Ingresos diarios de los últimos 7 días</p></div><span class="badge purple">Esta semana</span></div><div class="card-body"><div class="chart"><canvas id="sales-chart" aria-label="Ingresos diarios" role="img"></canvas></div><noscript>@foreach($labels as $i=>$label){{ $label }}: {{ $revenue[$i] }} €. @endforeach</noscript></div></section><section class="card"><div class="card-header"><div><h2>Inventario por categoría</h2><p>Unidades disponibles en tu tienda</p></div></div><div class="card-body"><div class="chart"><canvas id="stock-chart" aria-label="Unidades por categoría" role="img"></canvas></div><noscript>@foreach($categoryLabels as $i=>$label){{ $label }}: {{ $categoryStock[$i] }}. @endforeach</noscript></div></section></div>
<div class="grid-two"><section class="card"><div class="card-header"><div><h2>Últimas ventas</h2><p>La actividad más reciente de tu tienda</p></div><a class="btn secondary small" href="{{ route('sales') }}">Ver todas ↗</a></div><div class="table-wrap"><table><thead><tr><th>Venta / cliente</th><th>Fecha</th><th>Total</th><th>Estado</th></tr></thead><tbody>@forelse($recentSales as $sale)<tr><td><strong>#{{ str_pad($sale->id,4,'0',STR_PAD_LEFT) }}</strong><small>{{ $sale->customer }}</small></td><td>{{ $sale->created_at->format('d/m · H:i') }}</td><td><strong>{{ number_format($sale->total_cents/100,2,',','.') }} €</strong></td><td><span class="badge">Registrada</span></td></tr>@empty<tr><td colspan="4"><div class="empty"><h3>Tu primera venta empieza aquí</h3><p>Registra una venta para verla en el panel.</p></div></td></tr>@endforelse</tbody></table></div></section><section class="card"><div class="card-header"><div><h2>Necesitan reposición</h2><p>Evita quedarte sin tus productos</p></div><span class="badge warning">{{ $lowStock->count() }} alertas</span></div>@forelse($lowStock as $product)<div class="list-row"><div class="product-cell"><span class="product-icon">▧</span><div><strong>{{ $product->name }}</strong><small>{{ $product->sku }} · {{ $product->category->name }}</small></div></div><div class="text-right"><span class="badge warning">{{ $product->stock }} uds.</span><small>Mín. {{ $product->minimum_stock }}</small></div></div>@empty<div class="empty"><h3>Existencias al día</h3><p>No hay productos por debajo del mínimo.</p></div>@endforelse<div class="card-body"><a class="btn secondary small" href="{{ route('products',['low'=>1]) }}">Revisar inventario →</a></div></section></div>
@endsection
@push('scripts')<script src="{{ asset('js/chart.umd.min.js') }}"></script><script>
Chart.defaults.font.family="'DM Sans', sans-serif";Chart.defaults.color='#7d8799';Chart.defaults.animation=false;new Chart(document.getElementById('sales-chart'),{type:'line',data:{labels:@json($labels),datasets:[{label:'Ingresos (€)',data:@json($revenue),borderColor:'#6658e8',backgroundColor:'#6658e815',fill:true,tension:.35,borderWidth:2.5,pointRadius:4,pointBackgroundColor:'#fff',pointBorderWidth:2}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{x:{grid:{display:false},border:{display:false}},y:{beginAtZero:true,border:{display:false},grid:{color:'#f0f2f6'},ticks:{callback:v=>v+' €'}}}}});new Chart(document.getElementById('stock-chart'),{type:'doughnut',data:{labels:@json($categoryLabels),datasets:[{data:@json($categoryStock),backgroundColor:['#6658e8','#42bda7','#f5b96d','#6ca9f2'],borderWidth:5,borderColor:'#fff'}]},options:{responsive:true,maintainAspectRatio:false,cutout:'76%',plugins:{legend:{position:'bottom',labels:{usePointStyle:true,padding:20,font:{size:11}}}}}});
</script>@endpush
