<!DOCTYPE html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>@yield('title', 'Panel') · Stockia</title><link rel="stylesheet" href="{{ asset('css/inventory.css') }}"></head><body>
@auth
<div class="overlay" id="overlay"></div><aside class="sidebar" id="sidebar"><a class="brand" href="{{ route('dashboard') }}"><span class="brand-mark">▥</span><span>stockia<small>GESTIÓN DE COMERCIO</small></span></a><div class="nav-label">ESPACIO DE TRABAJO</div><nav class="nav" aria-label="Menú principal">@foreach([['dashboard','◫','Vista general'],['products','▦','Productos'],['sales','↗','Ventas'],['movements','⇄','Movimientos']] as [$route,$icon,$label])<a href="{{ route($route) }}" class="{{ request()->routeIs($route) ? 'active' : '' }}" @if(request()->routeIs($route)) aria-current="page" @endif><span class="nav-icon" aria-hidden="true">{{ $icon }}</span>{{ $label }}</a>@endforeach</nav><div class="side-bottom"><p style="color:#a3adbf;font-size:12px">Todo tu negocio,<br>en un mismo lugar.</p><div class="profile"><span class="avatar">{{ mb_substr(auth()->user()->name,0,1) }}</span><div><strong>{{ auth()->user()->name }}</strong><small>{{ auth()->user()->isAdmin() ? 'Administrador' : 'Empleado' }}</small><form method="POST" action="{{ route('logout') }}">@csrf<button type="submit">Cerrar sesión ↗</button></form></div></div></div></aside>
<div class="workspace"><header class="topbar"><button class="menu-toggle" id="menu-toggle" aria-expanded="false" aria-controls="sidebar" aria-label="Abrir menú">☰</button><span class="mobile-brand">stockia</span><div class="crumb">Mi comercio / @yield('title', 'Vista general')</div><div class="top-right"><span class="demo-pill">● Entorno de demostración</span><span class="avatar">{{ mb_substr(auth()->user()->name,0,1) }}</span></div></header><main class="main">
@if(session('success'))<div class="alert" role="status">{{ session('success') }}</div>@endif
@if($errors->any())<div class="alert error" role="alert"><strong>Revisa estos datos antes de continuar.</strong><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
@yield('content')<div class="footer-note"><span>Stockia · Control sin complicaciones</span><span>Datos de ejemplo. Sin pagos reales.</span></div></main></div>
<script>document.querySelectorAll('table').forEach(table=>{const labels=Array.from(table.querySelectorAll('th'),th=>th.textContent);table.querySelectorAll('tbody tr').forEach(tr=>Array.from(tr.children).forEach((td,i)=>td.dataset.label=labels[i]||''))});const toggle=document.getElementById('menu-toggle'),side=document.getElementById('sidebar'),overlay=document.getElementById('overlay');function menu(open){side.classList.toggle('open',open);overlay.classList.toggle('open',open);toggle.setAttribute('aria-expanded',String(open));toggle.setAttribute('aria-label',open?'Cerrar menú':'Abrir menú')}toggle.addEventListener('click',()=>menu(!side.classList.contains('open')));overlay.addEventListener('click',()=>menu(false));document.addEventListener('keydown',e=>{if(e.key==='Escape')menu(false)});</script>
@else @yield('content') @endauth
@stack('scripts')</body></html>
